name: project_nlp_env
channels:
- defaults
dependencies:
- python=3.13.5
- pip
- aiohttp
- aiosignal
- attrs
- certifi
- cffi
- charset-normalizer
- filelock
- frozenlist
- idna
- joblib
- matplotlib
- multidict
- multiprocess
- numpy
- packaging
- pandas
- pillow
- plotly
- protobuf
- pyarrow
- pyyaml
- requests
- safetensors
- scikit-learn
- seaborn
- setuptools
- six
- streamlit
- tokenizers
- torch
- tqdm
- transformers
- typing-extensions
- urllib3
- yarl
- pip:
  - alembic==1.16.4
  - altair==5.5.0
  - annotated-types==0.7.0
  - anyio==4.10.0
  - argon2-cffi==25.1.0
  - argon2-cffi-bindings==25.1.0
  - arrow==1.3.0
  - astroid==3.3.11
  - async-lru==2.0.5
  - babel==2.17.0
  - beautifulsoup4==4.13.5
  - black==25.1.0
  - bleach==6.2.0
  - blinker==1.9.0
  - cachetools==5.5.2
  - cloudpickle==3.1.1
  - cryptography==45.0.6
  - databricks-sdk==0.64.0
  - defusedxml==0.7.1
  - distro==1.9.0
  - docker==7.1.0
  - dotenv==0.9.9
  - fastapi==0.116.1
  - fastjsonschema==2.21.2
  - flask==3.1.2
  - fqdn==1.5.1
  - gitdb==4.0.12
  - gitpython==3.1.45
  - google-auth==2.40.3
  - graphene==3.4.3
  - graphql-core==3.2.6
  - graphql-relay==3.2.0
  - greenlet==3.2.4
  - h11==0.16.0
  - httpcore==1.0.9
  - httpx==0.28.1
  - importlib-metadata==8.7.0
  - ipywidgets==8.1.7
  - isoduration==20.11.0
  - isort==6.0.1
  - itsdangerous==2.2.0
  - jinja2==3.1.6
  - jiter==0.10.0
  - json5==0.12.1
  - jsonpointer==3.0.0
  - jsonschema==4.25.1
  - jsonschema-specifications==2025.4.1
  - jupyter==1.1.1
  - jupyter-console==6.6.3
  - jupyter-events==0.12.0
  - jupyter-lsp==2.2.6
  - jupyter-server==2.17.0
  - jupyter-server-terminals==0.5.3
  - jupyterlab==4.4.6
  - jupyterlab-code-formatter==3.0.2
  - jupyterlab-pygments==0.3.0
  - jupyterlab-server==2.27.3
  - jupyterlab-widgets==3.0.15
  - lark==1.2.2
  - mako==1.3.10
  - markupsafe==3.0.2
  - mccabe==0.7.0
  - mistune==3.1.3
  - mlflow==3.3.1
  - mlflow-skinny==3.3.1
  - mlflow-tracing==3.3.1
  - mpmath==1.3.0
  - mypy-extensions==1.1.0
  - narwhals==2.2.0
  - nbclient==0.10.2
  - nbconvert==7.16.6
  - networkx==3.5
  - ngrok==1.5.1
  - notebook==7.4.5
  - notebook-shim==0.2.4
  - openai==1.101.0
  - opentelemetry-api==1.36.0
  - opentelemetry-sdk==1.36.0
  - opentelemetry-semantic-conventions==0.57b0
  - p2j==1.3.2
  - pandocfilters==1.5.1
  - pathspec==0.12.1
  - pyasn1==0.6.1
  - pyasn1-modules==0.4.2
  - pydantic==2.11.7
  - pydantic-core==2.33.2
  - pydeck==0.9.1
  - pylint==3.3.8
  - python-dotenv==1.1.1
  - python-json-logger==3.3.0
  - pywinpty==3.0.0
  - referencing==0.36.2
  - rfc3339-validator==0.1.4
  - rfc3986-validator==0.1.1
  - rfc3987-syntax==1.1.0
  - rpds-py==0.27.0
  - rsa==4.9.1
  - scipy==1.16.1
  - send2trash==1.8.3
  - sentence-transformers==5.1.0
  - sentencepiece==0.2.1
  - smmap==5.0.2
  - sniffio==1.3.1
  - soupsieve==2.7
  - sqlalchemy==2.0.43
  - sqlparse==0.5.3
  - starlette==0.47.3
  - sympy==1.14.0
  - tenacity==9.1.2
  - terminado==0.18.1
  - threadpoolctl==3.6.0
  - tinycss2==1.4.0
  - toml==0.10.2
  - tomlkit==0.13.3
  - types-python-dateutil==2.9.0.20250822
  - typing-inspection==0.4.1
  - uri-template==1.3.0
  - uvicorn==0.35.0
  - waitress==3.0.2
  - watchdog==6.0.0
  - webcolors==24.11.1
  - webencodings==0.5.1
  - websocket-client==1.8.0
  - werkzeug==3.1.3
  - widgetsnbextension==4.0.14
  - zipp==3.23.0